# .travis.yml (Travis CI)
#
# Qxlnt
# https://github.com/j2doll/Qxlnt
#

language: c++
compiler: gcc
sudo: require
dist: trusty

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev 
 - sudo apt-get install qt5-default qttools5-dev-tools

install:

script:
  - cd Qxlnt
  - qmake Qxlnt.pro
  - make
  
  - cd ../HelloQXlnt
  - qmake HelloQXlnt.pro
  - make
  - ./HelloQXlnt

  - cd ../Qxlnt.tests
  - qmake Qxlnt.test.pro
  - make
  - ./Qxlnt.test

after_success:
