#
# Qxlnt
#

language: c++
compiler: gcc
sudo: require
dist: trusty # Ubuntu Xenial 16.04, Trusty 14.04, Precise 12.04

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

  # Qt5
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools qtbase5-private-dev  

script:
  # test
  - cd Qxlnt.tests
  - qmake Qxlnt.test.pro
  - make
  - ./Qxlnt.test



